---
title: "Day 3 Vectors"
author: "Jordan"
format: html
editor: visual
---

## Create some vectors in R 

Character string elements 
```{r}
# vectors must contain elements of the same data type 
marmots <- c("blue", "green", 4, "yellow")
# character strings like blue and green are wrapped in quotes. 4 is a numeric value no quotes needed.

# return it ----
marmots
# It has turned 4 into a character string. They need to all be the same data type. If there is one character and the rest are numbers, it will turn everything into characters. 
```

Numeric elements 
```{r}
pika <- c(12.4, 6.8, 2.9, 8.8, 5)
pika
# All numeric values
```

Integer elements 
```{r}
bear <- c(20L, 3L, 5L, 18L, 23L)
bear
# The L allows them to remain as integers instead of numeric. Without the L, 20 would appear as "20.0"
```

## Vector math 

Create some vectors 
```{r}
ringtail <- c(4.3, 8.9, 2.6, 7.1)
fox <- c(9.0, 12.5, 5.4, 10.9)

# add ----
ringtail + fox 

# subtract ----
fox - ringtail 

# scalar multipliers ----
100 * ringtail

# dot product ----
ringtail %*% fox 
```



